services:
#    balance.example:
#        class: BalanceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

#    app.command.get_transactions:
#        class: BalanceBundle\Command\BalanceCommand
#        arguments: [ @doctrine.orm.entity_manager ]
#        tags:
#            -  { name: console.command }