<?php

namespace BalanceBundle\Repository;

/**
 * PurseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurseRepository extends \Doctrine\ORM\EntityRepository
{
}
